apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: YWRtaW4K # This is the base64 encoded value of "admin".
  MYSQL_ROOT_PASSWORD: YWRtaW4K # This is the base64 encoded value of "admin".
